 # For details on how this file works refer to:
 #   - https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  #  - Check for updates once a week
  #  - Group all updates into a single PR
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-actions:
        patterns: [ "*" ]

  # Maintain dependencies for TypeScript and JavaScript
  - package-ecosystem: "npm"
    directory: "/wrappers/javascript"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-patch"]

  # Maintain dependencies for Cargo Packages
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Cargo Packages
  - package-ecosystem: "cargo"
    directory: "./askar-crypto/fuzz"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
        
